### ISSUE TITLE
capture / refund

### ISSUE THREAD

**Issue by exit15** [Dreamvention/paypal#13]
I see that you added a link to paypal transaction page to capture / refund etc. Why not integrate it into the extension just like in the old Express Checkout. I would like someone to contact me regarding this, sent emails, to you, to Opencart, no response. Look for exit15 in your inbox.

**Comment by rsenmakh** [comment]
Could you be more specific? What do you mean under "just like in the old Express Checkout"? Could you provide us with more details?

**Comment by exit15** [comment]
hi,
I have sent the explanation to Artem, I think this is the case no: support request 28913.
The basic idea of express checkout is that you can basically manage everything from the OpenCart admin area: On the order detail screen there is a new tab below the history section that has to do with PayPal transactions. There one can perform the following: Capture / Partial Capture / Void / Refund / Partial Refund. Naturally there are different checks to make sure you dont try to capture more than the authorized amount or refund more that the amount that was captured regardless if the full amount was captured or a partial amount was captured.

**Comment by rsenmakh** [comment]
All this functionality has been implemented.
Please use the latest version of the module.
