### ISSUE TITLE
[OC 3.0.x.x] Issues With Pay Later Settings

### ISSUE THREAD

**Issue by WebSpectrum** [Dreamvention/paypal#21]
There seem to be some issue with OPencart 3.0.x.x and the latest version of the extenion. Pay Later settings not being..

**Comment by rsenmakh** [comment]
This Pay Later option is only available for merchants from Australia, Germany, Spain, France, the United Kingdom, Italy, and the United States. Does your account belong to any country from the list?

**Comment by mhcwebdesign** [comment]
@WebSpectrum : Take a look at this issue: https://github.com/Dreamvention/paypal/issues/25 
I think we found the reason why there were problems with the missing Pay Later button.
