### ISSUE TITLE
[3.0.0] Sofort Payment

### ISSUE THREAD

**Issue by osworx** [Dreamvention/paypal#22]
While Sofort has been bought by Klarna a few years ago (!!), the logic would be now, that Klarna can be offered.
But the language string is completely removed now, does that mean that Klarna (Sofort) is not available anymore?

**Comment by rsenmakh** [comment]
Yes. We have removed Sofort from the module. It's not available anymore.

**Comment by osworx** [comment]
Then such removements should be announced clearly because some shop owners rely on that payment type.

**Comment by rsenmakh** [comment]
It is not within our control. PayPal informed us that Sofort had to be removed, so we promptly took it down.
