### ISSUE TITLE
[3.x.x] PayPal Later still not working (V3.0.1)

### ISSUE THREAD

**Issue by mhcwebdesign** [Dreamvention/paypal#25]
Why is it so hard to get a working PayPal Later? See attached screenshots, just tested your V3.0.1 on [OpenCart 3.0.x.x](https://github.com/opencart/opencart/tree/3.0.x.x)

There are probably other flaws, but this is a most obvious one.

When will there be a stable release?

Alternatively, if you can't fix it, then remove PayPal Later feature. Or we are going to remove your PayPal Integration altogether in the upcoming OpenCart 3.0.4.0 and go for another Paypal extension.
![Screenshot_2024-03-19_23-04-02](https://github.com/Dreamvention/paypal/assets/2989557/7a316bfc-7175-4320-8a44-199263e66bb4)
![Screenshot_2024-03-19_23-00-55](https://github.com/Dreamvention/paypal/assets/2989557/e785d130-ba78-42a9-a662-a5c07496a60c)
![Screenshot_2024-03-19_23-00-15](https://github.com/Dreamvention/paypal/assets/2989557/3f1da219-5bb9-40b8-97e7-edbd047a6738)

**Comment by rsenmakh** [comment]
We are only able to test the PayLater feature in SandBox mode. Our Estonian production account does not support this feature.
Please take a look at the video [OpenCart 3.0.3.8 - PayLater](https://youtu.be/hv7rclr486E)

This feature is only available for merchants from: Australia, Germany, Spain, France, the United Kingdom, Italy, and the United States. And even if the merchant, for example, is from the USA, and the client visited the site from Ukraine, the client will not see the Pay Later button.

**Comment by mhcwebdesign** [comment]
@rsenmakh : I did that, for a UK-based site and location, with a UK-based PayPal account. The checkout sequence correctly offers the **Buy Now Pay Later with PayPal** payment method, but the final checkout step (Confirm Order) only generates an empty button, with the following code:

```
<div id="paypal_form">
	<div id="paypal_button" class="paypal-button clearfix" style="text-align: right;">
		<div id="paypal_button_container" class="paypal-button-container" style="display: inline-block; width: 350px;"></div>
	</div>
</div>
<script type="text/javascript">

if (typeof PayPalAPI !== 'undefined') {
	PayPalAPI.init();
}
	
</script>

```
Have you actually tested it at all?

**Comment by rsenmakh** [comment]
Hey, did you read my message?
Did you watch the video I sent?
Do you still have a question if we tested it?

**Comment by mhcwebdesign** [comment]
Yes, I watched your video. As I said, the Pay Later buttons aren't generated anywhere, neither on the product page, nor in the checkout sequence, even though I enabled it via the admin backend, see attached screenshot.
![Screenshot_2024-03-20_13-28-43](https://github.com/Dreamvention/paypal/assets/2989557/04aebaca-46c2-4fce-bd3c-5d7d916d3e83)

**Comment by rsenmakh** [comment]
You have enabled the "Pay Later" message, but you have not enabled the "Pay Later" button.
Please click on the following link to view the screenshot: 
https://prnt.sc/CIHZBWZ0V5an

**Comment by mhcwebdesign** [comment]
Yes, already enabled for checkout, cart, and product, see screenshot.
![Screenshot_2024-03-20_13-41-55](https://github.com/Dreamvention/paypal/assets/2989557/071ab7b3-709c-4fb0-8e60-741d0beb9aba)

**Comment by mhcwebdesign** [comment]
Further to this, I also enabled debug logging, but the **paypal.log** has no entries. It correctly uses the **paypal_later.twig**, and calls the **PayPalAPI.init();**

Is there anything else I need to look into, to find out why it won't generate the expected Pay Later button?

**Comment by rsenmakh** [comment]
You are right. It depends on the currency as well.
We will fix it.

**Comment by mhcwebdesign** [comment]
> You are right. It depends on the currency as well. We will fix it.

Thanks for looking into it. After the bugfix, could you also change the version to e.g. 3.0.2, to avoid confusions?
Let me know when done, so we can integrate it into the upcoming OC 3.0.4.0.

**Comment by rsenmakh** [comment]
Hi @mhcwebdesign ,
The extension has been updated on GitHub
https://github.com/Dreamvention/paypal/releases/tag/v3.0.2

Please check the default country and default currency in the extension settings.
<img width="547" alt="image" src="https://github.com/Dreamvention/paypal/assets/48048035/726d64dd-a40f-45d1-b438-a1c4ceeb68a3">

**Comment by mhcwebdesign** [comment]
Thanks. Just tested it, and it works fine, much appreciated. I have now updated the [url=https://github.com/opencart/opencart/tree/3.0.x.x]OpenCart 3.0.x.x[/url] branch accordingly.
