### ISSUE TITLE
[3.x.x branch] Wrong heading title in sale/order/info

### ISSUE THREAD

**Issue by mhcwebdesign** [Dreamvention/paypal#26]
When the payment extension PayPal Checkout Integration is enabled on an OpenCart 3.0.x.x version, e.g. https://github.com/opencart/opencart/tree/3.0.x.x , the heading title is wrong on the admin backend's sale/order/info page. It always shows this:

![Screenshot_2024-05-31_12-00-31](https://github.com/Dreamvention/paypal/assets/2989557/d430a380-05c2-4db6-a50a-e00300bd5ccd)

It should show this:
![Screenshot_2024-05-31_12-02-08](https://github.com/Dreamvention/paypal/assets/2989557/62937582-bc67-4abc-b097-40f43f99942e)
 
This issue is caused by the event handler **order_info_before** in file **admin/controller/extension/payment/paypal.php** which calls the `$this->load->language('extension/payment/paypal');` . Later on, OpenCart calls the event handler **event/language/before** (see file **admin/controller/event/language.php**) which then loads the wrongly modified data from the **$this->language->data** .

Suggested bugfix for admin/controller/extension/payment/paypal.php :

```
	public function order_info_before($route, &$data) {
		.....
		$this->load->language('extension/payment/paypal','extension_payment_paypal');
		.....
		$data['tabs'][] = array(
			'code'    => 'paypal',
			'title'   => $this->language->get('extension_payment_paypal')->get('heading_title_main'),
			'content' => $this->load->view('extension/payment/paypal/order', $data)
		);
		.....
	}
```

**Comment by mhcwebdesign** [comment]
I might add, the same issue probably also exists for OpenCart 4.0.x.x or OpenCart 2.3.x.x versions, though I haven't tested them, was busy on maintaining the [OC 3.0.x.x](https://github.com/opencart/opencart/tree/3.0.x.x) branch.

**Comment by exit15** [comment]
The issue still exits. I downloaded V3.16 and then 3.17 (for OpenCart 3.0.4)
Dreamvention has to make the change or it will pop up again and again.

**Comment by mhcwebdesign** [comment]
Please open it as a new issue on Dreamvention's site at https://github.com/Dreamvention/paypal .

BTW.: it works fine for OpenCart 3.0.4.0 if you use its already built-in PayPal Integration extension.
