### ISSUE TITLE
Missing fuctionality

### ISSUE THREAD

**Issue by exit15** [Dreamvention/paypal#3]
Hi guys, how is one supposed to capture payments if using "authorization" method? how to void, refund. All of the above is part of Express Checkout. Why was it dropped? Any plans to add this?

**Comment by kenkit** [comment]
I'm using the sale method but getting trouble with customers having their order not complete. I have to manually change to complete so the customer can access the goods/services.
Just updated the extension on my store, not sure if that's been fixed

**Comment by exit15** [comment]
Never got to that far. You probably need to toy around with order status configuration to see which one would yield the "completed" status you want.
Otherwise, no word from the developers likely due to the war in the Ukraine ;(

**Comment by rsenmakh** [comment]
All this functionality has been implemented.
