### ISSUE TITLE
URGENT ISSUE! "Sorry, PayPal is currently busy. Please try again later! Please choose another payment method or contact us."

### ISSUE THREAD

**Issue by ViX-Sicilian** [Dreamvention/paypal#32]
![paypal-issue](https://github.com/user-attachments/assets/89fd844c-2621-4c0c-a4d6-4c4898aae099)
There's an issue with this module at the moment, really needs an urgent fix.

Others have reported it too here: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=38358

**Comment by rsenmakh** [comment]
PayPal does not accept some requests if the HTTP/2 protocol is used. They are resolving this issue right now.
But as a quick solution, you can do the following:
- Open the file system/library/paypal/paypal.php
- Find the line CURLOPT_TIMEOUT => 10
- After it, add the line CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1
